on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python Script
        run: python main.py https://acquageraci.forumfree.it/\?f=6409732
